app = "vectrahub"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"
  
[deploy]
  release_command = "echo 'Deployment starting...'"
  strategy = "rolling"

[env]
  PATH = "/opt/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  PYTHONPATH = "/var/www/html"
  APP_ENV = "production"
  APP_NAME = "VectraHub"
  APP_URL = "https://vectrahub.fly.dev"
  SUPABASE_URL = "https://ozjbgmcxocvznfcttaty.supabase.co"
  UPLOAD_MAX_SIZE = "52428800"
  SESSION_LIFETIME = "86400"
  CSRF_TOKEN_EXPIRY = "3600"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "90s"    # Extended grace period for PHP/Python startup
    interval = "30s"        # Check every 30 seconds
    method = "GET"
    timeout = "20s"         # Longer timeout for initial health checks
    path = "/health"        # Health check endpoint (no redirects)
    protocol = "http"
    tls_skip_verify = false
    headers = {}            # No special headers needed

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 2048

[mounts]
  source = "uploads"
  destination = "/var/www/html/uploads"